[[check]]
type = "Exclude"
id = "STAN-0205"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0208"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0103"
file = "src/Gyler/Data/NonEmptyText.hs"
