{-# LANGUAGE TemplateHaskellQuotes #-}
{-# LANGUAGE DataKinds #-}

-- This file is auto-generated by scripts/create_template_files.sh.
-- Do not edit by hand.
module Gyler.Serialize.UniqID.All (allUniqIDTypes) where

import Language.Haskell.TH (TypeQ)

import Gyler.Domain.RPM
import Gyler.Domain.RPM.Name
import Gyler.Domain.RPM.EVR
import Gyler.Domain.RPM.EVR.Version
import Gyler.Domain.RPM.EVR.Release
import Gyler.Domain.RPM.EVR.Epoch

allUniqIDTypes :: [TypeQ]
allUniqIDTypes =
    [t| RPM 'WithEVR |] :
    [t| RPM 'NoEVR   |] :
    [t| Name |] :
    [t| EVR |] :
    [t| Version |] :
    [t| Release |] :
    [t| Epoch |] :
    []

