#!/bin/bash
# ------------------------------------------------------------
# create_template_files.sh
#
# Description:
#   Create template files for Gyler.
#
#   List of modules created by this script:
#       Gyler.Serialize.UniqID.All
#
# Usage:
#   ./find_id_serializers.sh             # Create modules.
#   ./find_id_serializers.sh --stdout    # Print modules text to stdout. Useful for debug.
#
# ------------------------------------------------------------
set -euo pipefail

SCRIPT_NAME="create_template_files.sh"

print_error() {
    # Print error messages to stderr with script name prefix
    printf "%s:\t%b\n" "$SCRIPT_NAME" "$*" >&2
}

script_dir="$(dirname "$0")"

uniqIDAll() {
    MODULE="src/Gyler/Serialize/UniqID/All.hs"
    echo "Writing to $MODULE..."

    case "$1" in
        --to-file)
            OUT="$MODULE";;
        --stdout)
            OUT="/dev/stdout";;
    esac

    imports="$("$script_dir"/find_id_serializers.sh --modules \
        | sed 's|^|import |g')"

    types="$("$script_dir"/find_id_serializers.sh --types \
        | sed 's|$| :|g'     \
        | sed 's|^|    |g')"

    cat << EOF > "$OUT"
{-# LANGUAGE TemplateHaskellQuotes #-}
{-# LANGUAGE DataKinds #-}

-- This file is auto-generated by scripts/create_template_files.sh.
-- Do not edit by hand.
module Gyler.Serialize.UniqID.All (allUniqIDTypes) where

import Language.Haskell.TH (TypeQ)

$imports

allUniqIDTypes :: [TypeQ]
allUniqIDTypes =
$types
    []
EOF
}

main() {
    if [[ $# -eq 0 ]]; then
        print_error "Usage: $SCRIPT_NAME [--stdout|--to-files]"
        exit 1
    fi

    mode="--to-file"

    case "$1" in
        --stdout)
            mode="--stdout"
            ;;
        --to-file)
            mode="--to-file"
            ;;
        *)
            print_error "Unknown option: $1"
            exit 1
            ;;
    esac

    uniqIDAll "$mode"
}

main "$@"

